export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_ID!;
export const IMAGES_BUCKER_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKER_ID!;
